In [1]:
import numpy as np
import networkx as nx
from nx_landmarks import landmarks

In [2]:
G = nx.watts_strogatz_graph(n = 10, k = 10, p = 0.5, seed = 10)
D = landmarks(G,2,"rand",h = 1)
D.get_landmarks()

In [3]:
D.embeddings

array([[1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
D.landmark_ranking

array([2, 5, 8, 6, 4, 1, 0, 9, 7, 3])

In [8]:
D.landmarks

array([2, 5, 8])

In [6]:
D.add_landmarks()

In [7]:
np.array([D.embeddings[d] for d in D.landmarks])

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [10]:
D.landmarks

array([3, 0, 5])

In [9]:
D.embeddings

array([[1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
phi = np.array([1,2,3,4,5])

In [9]:
a = phi.reshape(-1,1)+phi.reshape(1,-1)

In [15]:
len(a.flatten())

25

In [14]:
len(np.where(a == b)[0])

25